FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DEFAULT_TIMEOUT=1200 \
    PIP_RETRIES=10

COPY requirements.txt ./
RUN pip install --default-timeout=1200 --retries 10 --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "branch_backend/app.py"]
